# Generated by Django 3.1.2 on 2021-05-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_auto_20210511_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Snippet',
            field=models.CharField(default='click above to read', max_length=255),
        ),
    ]
