# Generated by Django 3.1.2 on 2021-05-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
