# Generated by Django 3.1.2 on 2021-05-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0016_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_value',
            new_name='body',
        ),
    ]
