# Generated by Django 3.1.2 on 2021-05-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0019_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
