# Generated by Django 3.1.2 on 2021-05-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0020_remove_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default/pp.png', null=True, upload_to='images/profile/'),
        ),
    ]
