# Generated by Django 3.1.2 on 2021-05-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0022_auto_20210520_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default/pp.jpg', null=True, upload_to='images/profile/'),
        ),
    ]
